model:
  type: "SubspaceConceptLattice"
  config:
    embed_dim: 128
    ambient_dim: 10
    n_obj: 4
    n_attr: 2
    image_size: 64
    image_channels: 3
    lbd: 0.05
    max_samples_per_cardinality: 10
    intersection_power_steps: 5
    maximize_singleton_attr_rank: True
    intersection_consistency_only_pairs: True
    perceptual_encoder:
      type: "ViTEncoder"
      config:
        patch_size: 8
        depth: 4
        heads: 8
        mlp_ratio: 4.0
    concept_encoder:
      type: "ConceptEncoder"
      config:
        mapping_type: "linear"
        heads: 8
    decoder:
      type: "ViTDecoder"
      config:
        patch_size: 8
        depth: 4
        heads: 8
        mlp_ratio: 4.0
    loss_weights:
      reconstruction_loss: 1.0
      singleton_obj_rank_loss: 1.0
      max_singleton_attr_rank_loss: 1.0
      modular_subspace_loss: 1.0
      attr_orthogonality_loss: 1.0
      concept_similarity_loss: 0.0
      union_consistency_loss: 1.0
      intersection_consistency_loss: 1.0
      galois_attr_loss: 1.0
      galois_obj_loss: 1.0
      loss_obj_card_prop: 0.0
      loss_attr_card_inv_prop: 0.0
      loss_attr_obj_inv_prop: 0.0
      repulsion_loss_obj: 1.0
      repulsion_loss_attr: 1.0
    
data:
  train:
    type: v0Dataset
    config:
      image_size: [64, 64]
      shapes: ["circle", "square"]
      colors: ["red", "blue"]
      excluded_combinations: []
      num_samples: 1000
      return_metadata: True
      center_range: [32, 33]
      size_range: [20, 21]
    dataloader_config:
      batch_size: 8
      shuffle: True

trainer:
  max_epochs: 100
  optimizer:
    type: Adam
    config:
      lr: 0.0001
