import matplotlib.pyplot as plt
import numpy as np

# We want to focus on "Red Circle", "Red Square", "Red", and "Universal" Concepts
targets = ["(Universal)", "(Red)", "(Red Circle)", "(Red Square)"]
keys_to_plot = []

# Find the exact keys in the concept_mapping generated by the previous cell
for target in targets:
    for k in concept_mapping.keys():
        if target in k:
            keys_to_plot.append(k)
            break

# Create a figure with a row for each target concept and 2 columns (X_attr and X_obj)
fig, axes = plt.subplots(len(keys_to_plot), 2, figsize=(16, 4 * len(keys_to_plot)))

for i, key in enumerate(keys_to_plot):
    # concept_mapping[key]["X_attr"] and ["X_obj"] have shape (n_attr/n_obj, d_ambient)
    x_attr = concept_mapping[key]["X_attr"].cpu().numpy()
    x_obj = concept_mapping[key]["X_obj"].cpu().numpy()
    
    # Ensure 2D for iteration over basis vectors
    if x_attr.ndim == 1:
        x_attr = x_attr[np.newaxis, :]
    if x_obj.ndim == 1:
        x_obj = x_obj[np.newaxis, :]
        
    ax_attr = axes[i, 0]
    ax_obj = axes[i, 1]
    
    n_attr, d_ambient_attr = x_attr.shape
    bar_width_attr = 0.8 / n_attr
    for r in range(n_attr):
        ax_attr.bar(np.arange(d_ambient_attr) + r * bar_width_attr, x_attr[r], 
                    width=bar_width_attr, alpha=0.7, label=f"Basis {r}")
    ax_attr.set_title(f"X_attr: {key}")
    ax_attr.set_xlabel("Dimension Index")
    ax_attr.set_ylabel("Value")
    if n_attr > 1:
        ax_attr.legend()
        
    n_obj, d_ambient_obj = x_obj.shape
    bar_width_obj = 0.8 / n_obj
    for r in range(n_obj):
        ax_obj.bar(np.arange(d_ambient_obj) + r * bar_width_obj, x_obj[r], 
                   width=bar_width_obj, alpha=0.7, label=f"Basis {r}")
    ax_obj.set_title(f"X_obj: {key}")
    ax_obj.set_xlabel("Dimension Index")
    ax_obj.set_ylabel("Value")
    if n_obj > 1:
        ax_obj.legend()

plt.tight_layout()
plt.show()
